# Generated by Django 4.2.4 on 2023-09-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis_app', '0002_signup_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='nationality',
            field=models.CharField(default='', max_length=255),
        ),
    ]
