# Generated by Django 4.2.4 on 2023-09-06 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tennis_app', '0004_signup_handbat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='fname',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='lname',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='PlayerRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('first_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_name', to='tennis_app.signup', to_field='fname')),
                ('last_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_name', to='tennis_app.signup', to_field='lname')),
            ],
        ),
    ]
