# Generated by Django 4.2.4 on 2023-09-06 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tennis_app', '0007_remove_playerranking_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('givenName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tennis_app.signup', to_field='fname')),
            ],
        ),
    ]
