# Generated by Django 4.2.4 on 2023-09-06 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tennis_app', '0008_playerranking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlayerRanking',
        ),
    ]
