# Generated by Django 4.2.4 on 2023-09-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis_app', '0010_playerranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerranking',
            name='leaguetype',
            field=models.CharField(default='', max_length=255),
        ),
    ]
