# Generated by Django 4.2.4 on 2023-09-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis_app', '0011_playerranking_leaguetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='imageurl',
            field=models.TextField(default=''),
        ),
    ]
