# Generated by Django 4.2.4 on 2023-09-16 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis_app', '0012_signup_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='currenteam',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='signup',
            name='datelastchamp',
            field=models.DateField(default='2023-01-01'),
        ),
        migrations.AddField(
            model_name='signup',
            name='favoriteplayer',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='signup',
            name='lastchamp',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='signup',
            name='locatelastchamp',
            field=models.TextField(default=''),
        ),
    ]
