# Generated by Django 4.2.4 on 2023-09-16 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis_app', '0013_signup_currenteam_signup_datelastchamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='datelastchamp',
            field=models.DateField(default='0000-00-00'),
        ),
    ]
