# Generated by Django 4.2.4 on 2023-09-16 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis_app', '0014_alter_signup_datelastchamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='datelastchamp',
            field=models.DateField(default='2023-01-01'),
        ),
    ]
