# Generated by Django 4.2.4 on 2023-09-16 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tennis_app', '0015_alter_signup_datelastchamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerranking',
            name='firstname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tennis_app.signup'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='fname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='signup',
            name='lname',
            field=models.CharField(max_length=255),
        ),
    ]
