# Generated by Django 4.2.4 on 2023-09-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis_app', '0016_alter_playerranking_firstname_alter_signup_fname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
