# Generated by Django 4.2.4 on 2023-09-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis_app', '0019_uploadimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploadVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videodescription', models.TextField()),
                ('videourl', models.TextField()),
            ],
        ),
    ]
