# Generated by Django 4.2.4 on 2023-09-19 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tennis_app', '0020_uploadvideos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='uploadVideos',
            new_name='UploadTournamentVideos',
        ),
    ]
